# Generated by Django 4.0.4 on 2022-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0005_remove_cuisines_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines_category',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
