# Generated by Django 4.0.4 on 2022-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0006_alter_cuisines_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisines_category',
            name='desp',
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='actual_price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='discount',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='extra_offer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='price_range',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
