# Generated by Django 4.0.4 on 2022-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0007_remove_cuisines_category_desp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines_category',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuisines_category',
            name='extra_offer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
